spring:
  application:
    name: SplitifyExpenses
    version: 0.0.1
  datasource:
    url: jdbc:postgresql://localhost:5430/splitify-expenses-db
    username: mihanizzm
    password: sdf82ldskfU823s6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  